### PR TITLE
Finnish translations, minor general translation fixes

### PR DESCRIPTION
**Pull request by mookkari**
- Added: Finnish translations
- Fix: "Schedule Thursday" was newer translated because of typo. Because of this corresponding entity name was misleading.
- Fix: "Schedule Friday" fixed to same form as others
- Fix: typo in english translation "Dry countdown"

### CODE REVIEW

**Comment by mookkari** [comment]
I noticed one problem: 

It looks like my sunseeker integration now use ALWAYS Finnish language in my HA regardless if I change language in user settings to English (or Danish). After changing language I have removed browser cookies, restarted HA and added my lawn mover again. All entities are named based on Finnish language (e.g. entity switch for scheduling is switch.reino_ajastus). Entity titles are in Finnish but entity values are correctly in english if UI language is english. 

Still trying to figure out if this is HA problem, integration plugin bug or user error.

Cursor_and_Settings_–_Home_Assistant

**Comment by Sdahl1234** [comment]
I'm on holiday right now. I will have a look when I get home

**Comment by mookkari** [comment]
No hurry, enjoy your holiday! 

Just wanted to mention this issue so that it should be fixed before accepting pull request. Meanwhile I will try to debug the code.

**Comment by mookkari** [comment]
I studied the issue and the value of the variable _hass.config.language_ is the system language (Settings - System - General - Language), not the language value in the User settings. Some other integration plugins worked the same way, so I guess it is OK.

If I want the Sunseeker integration entity names in English, I should temporarily change the system language to English before adding a new Sunseeker device. After that, I can change back to Finnish. Devices under settings are always translated based on system language, not user language (UI language). Weird but it seems to work this way.

Anyway, from my perspective a pull request is ok to be merged with the main branch.

**Comment by Sdahl1234** [comment]
Thanks @mookkari

**Pull request merged**
